CommitMsg:
  CapitalizedSubject:
    enabled: false

  EmptyMessage:
    enabled: false

  TrailingPeriod:
    enabled: true

  TextWidth:
    enabled: false

PreCommit:
  ALL:
    exclude:
      - 'db/migrate/*'
    on_warn: fail

  AuthorEmail:
    enabled: true

  AuthorName:
    enabled: true

  MergeConflicts:
    enabled: true

  YamlSyntax:
    enabled: true

  BundleCheck:
    enabled: true

  RuboCop:
    enabled: true

  Fasterer:
    enabled: true

  BundleAudit:
    enabled: true

  Reek:
    enabled: true

  RailsBestPractices:
    enabled: false

PrePush:
  Brakeman:
    enabled: true

  RSpec:
    enabled: true
