AllCops:
  Exclude:
    - 'spec/**/*'
    - 'bin/*'
  TargetRubyVersion: 2.5

Metrics/LineLength:
  Max: 120

FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/api/v1/taxes_controller.rb'

require: rubocop-rspec
